---
tasks:
- name: engines/procurement/spec/features/inspection.feature:7
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/inspection.feature:7
- name: engines/procurement/spec/features/inspection.feature:45
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/inspection.feature:45
- name: engines/procurement/spec/features/inspection.feature:68
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/inspection.feature:68
- name: engines/procurement/spec/features/inspection.feature:101
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/inspection.feature:101
- name: engines/procurement/spec/features/inspection.feature:114
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/inspection.feature:114
- name: engines/procurement/spec/features/inspection.feature:152
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/inspection.feature:152
- name: engines/procurement/spec/features/inspection.feature:168
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/inspection.feature:168
- name: engines/procurement/spec/features/managing_requests.feature:7
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:7
- name: engines/procurement/spec/features/managing_requests.feature:39
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:39
- name: engines/procurement/spec/features/managing_requests.feature:56
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:56
- name: engines/procurement/spec/features/managing_requests.feature:83
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:83
- name: engines/procurement/spec/features/managing_requests.feature:103
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:103
- name: engines/procurement/spec/features/managing_requests.feature:130
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:130
- name: engines/procurement/spec/features/managing_requests.feature:149
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:149
- name: engines/procurement/spec/features/managing_requests.feature:164
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:164
- name: engines/procurement/spec/features/managing_requests.feature:190
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:190
- name: engines/procurement/spec/features/managing_requests.feature:202
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:202
- name: engines/procurement/spec/features/managing_requests.feature:219
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:219
- name: engines/procurement/spec/features/managing_requests.feature:242
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:242
- name: engines/procurement/spec/features/managing_requests.feature:261
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:261
- name: engines/procurement/spec/features/managing_requests.feature:288
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:288
- name: engines/procurement/spec/features/managing_requests.feature:299
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:299
- name: engines/procurement/spec/features/managing_requests.feature:312
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:312
- name: engines/procurement/spec/features/managing_requests.feature:323
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:323
- name: engines/procurement/spec/features/managing_requests.feature:334
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:334
- name: engines/procurement/spec/features/managing_requests.feature:347
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:347
- name: engines/procurement/spec/features/managing_requests.feature:370
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:370
- name: engines/procurement/spec/features/managing_requests.feature:391
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:391
- name: engines/procurement/spec/features/managing_requests.feature:411
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:411
- name: engines/procurement/spec/features/managing_requests.feature:424
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:424
- name: engines/procurement/spec/features/managing_requests.feature:439
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/managing_requests.feature:439
- name: engines/procurement/spec/features/periods_and_states.feature:4
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:4
- name: engines/procurement/spec/features/periods_and_states.feature:16
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:16
- name: engines/procurement/spec/features/periods_and_states.feature:25
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:25
- name: engines/procurement/spec/features/periods_and_states.feature:43
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:43
- name: engines/procurement/spec/features/periods_and_states.feature:58
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:58
- name: engines/procurement/spec/features/periods_and_states.feature:67
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:67
- name: engines/procurement/spec/features/periods_and_states.feature:75
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:75
- name: engines/procurement/spec/features/periods_and_states.feature:94
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:94
- name: engines/procurement/spec/features/periods_and_states.feature:112
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:112
- name: engines/procurement/spec/features/periods_and_states.feature:128
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:128
- name: engines/procurement/spec/features/periods_and_states.feature:143
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:143
- name: engines/procurement/spec/features/periods_and_states.feature:157
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/periods_and_states.feature:157
- name: engines/procurement/spec/features/procurement_groups.feature:4
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/procurement_groups.feature:4
- name: engines/procurement/spec/features/procurement_groups.feature:20
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/procurement_groups.feature:20
- name: engines/procurement/spec/features/procurement_groups.feature:27
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/procurement_groups.feature:27
- name: engines/procurement/spec/features/procurement_groups.feature:47
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/procurement_groups.feature:47
- name: engines/procurement/spec/features/procurement_groups.feature:56
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/procurement_groups.feature:56
- name: engines/procurement/spec/features/procurement_groups.feature:65
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/procurement_groups.feature:65
- name: engines/procurement/spec/features/roles.feature:4
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/roles.feature:4
- name: engines/procurement/spec/features/roles.feature:23
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/roles.feature:23
- name: engines/procurement/spec/features/roles.feature:47
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/roles.feature:47
- name: engines/procurement/spec/features/roles.feature:66
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/roles.feature:66
- name: engines/procurement/spec/features/templates.feature:7
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/templates.feature:7
- name: engines/procurement/spec/features/templates.feature:17
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/templates.feature:17
- name: engines/procurement/spec/features/templates.feature:32
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/templates.feature:32
- name: engines/procurement/spec/features/templates.feature:44
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/templates.feature:44
- name: engines/procurement/spec/features/templates.feature:57
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/templates.feature:57
- name: engines/procurement/spec/features/templates.feature:74
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/templates.feature:74
- name: engines/procurement/spec/features/templates.feature:94
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/templates.feature:94
- name: engines/procurement/spec/features/templates.feature:103
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/templates.feature:103
- name: engines/procurement/spec/features/users_and_organisations.feature:4
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:4
- name: engines/procurement/spec/features/users_and_organisations.feature:18
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:18
- name: engines/procurement/spec/features/users_and_organisations.feature:36
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:36
- name: engines/procurement/spec/features/users_and_organisations.feature:47
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:47
- name: engines/procurement/spec/features/users_and_organisations.feature:61
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:61
- name: engines/procurement/spec/features/users_and_organisations.feature:68
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:68
- name: engines/procurement/spec/features/users_and_organisations.feature:77
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:77
- name: engines/procurement/spec/features/users_and_organisations.feature:90
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:90
- name: engines/procurement/spec/features/users_and_organisations.feature:97
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:97
- name: engines/procurement/spec/features/users_and_organisations.feature:107
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/users_and_organisations.feature:107
