---
tasks:
- name: engines/procurement/spec/features/smoke_test.feature:4
  scripts:
    test:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec engines/procurement/spec/features/smoke_test.feature:4
