jobs:

  meta:

    name: Meta
    description: |
      Various superordinate quality assurance tasks

    depends-on:
    - type: job
      job: scenarios
      states: [passed]
    - type: job
      job: leihs-admin-scenarios
      states: [passed]

    run-on:
    - type: branch
      include-match: ^.*$

    context:
      task-defaults:
        max-auto-trials: 1
        traits:
          linux: true
          ruby: true

      tasks:
        increase-of-problematic-tests:
          name: "Number of problematic tests did not increase"
          scripts:
            main:
              body: ".cider-ci/bin/check_problematic_scenarios.rb"

        git-branch-current:
          name: "git tree contains latest commit from origin/master"
          scripts:
            main:
              body: ".cider-ci/bin/check_if_branch_current"
