_cider-ci_include:
  - .cider-ci/jobs/scenarios.yml
  - .cider-ci/jobs/leihs-admin-scenarios.yml
  - .cider-ci/jobs/problematic-scenarios.yml
  - .cider-ci/jobs/code-checks.yml
  - .cider-ci/jobs/leihs-admin-code-checks.yml
  - .cider-ci/jobs/procurement-code-checks.yml
  - .cider-ci/jobs/meta.yml
  - .cider-ci/jobs/good-to-merge.yml
