_cider-ci_include:
  - .cider-ci/jobs/tests-leihs.yml
  - .cider-ci/jobs/problematic-tests.yml
  - .cider-ci/jobs/tests-leihs-admin.yml
  - .cider-ci/jobs/meta.yml
  - .cider-ci/jobs/good-to-merge.yml
