jobs:

  admin-code-checks:

    name: 'Admin: Code Checks'

    description: |
      Run static checks and metrics: complexity, duplication, code format for Admin engine.

    run-on:
    - type: branch
      include-match: '[a-z]*/admin_.*$'
      exclude-match: '^(.*no-ci.*)$'
    - type: branch
      include-match: '^(.*master.*)$'
      exclude-match: '^(.*no-ci.*)$'


    context:

      _cider-ci_include:
        - cider-ci/shared/code-checks-context.yml

      tasks:

        lint_ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: bundle exec rubocop engines/leihs_admin/ -c engines/leihs_admin/.rubocop.yml
