jobs:

  core-scenarios:

    name: 'Core: Scenarios'

    description: |
      Run leihs features (except engines) under MRI

    run-on:
    - type: branch
      include-match: '[a-z]*/core_.*'
    - type: branch
      include-match: '[a-z]*/master.*'

    context:
      task-defaults:
        max-auto-trials: 3

      _cider-ci_include:
        - cider-ci/shared/tests-context.yml
        - cider-ci/tasks/cucumber_scenarios.yml
