jobs:

  procurement-scenarios:

    name: 'Procurement: Scenarios'

    description: |
      Run procurement engine scenarios under MRI

    priority: -1

    run-on:
    - type: branch
      include-match: '[a-z]*/procurement_.*$'
      exclude-match: '^(.*no-ci.*)$'
    - type: branch
      include-match: '^(.*master.*)$'
      exclude-match: '^(.*no-ci.*)$'

    context:
      task-defaults:
        max-auto-trials: 3

      _cider-ci_include:
        - cider-ci/shared/tests-context.yml
        - cider-ci/tasks/procurement_scenarios.yml
