jobs:

  procurement-code-checks:

    name: 'Procurement: Code Checks'

    description: |
      Run static checks and metrics: complexity, duplication, code format for Procurement engine.

    run-on:
    - type: branch
      include-match: '[a-z]*/procurement_.*$'
    - type: branch
      include-match: '[a-z]*/master.*'

    context:

      _cider-ci_include:
        - cider-ci/shared/code-checks-context.yml

      tasks:

        lint_ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: bundle exec rubocop engines/procurement/ -c engines/procurement/.rubocop.yml
